apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wp-wptest
  namespace: argocd
spec:
  destination:
    namespace: wordpress
    server: https://kubernetes.default.svc
  project: imprint
  source:
    repoURL: https://github.com/ocf/imprint-sites.git
    path: wordpress/wptest
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
